### PR TITLE
feat: Add ShopSearch component on large screen

### PR DESCRIPTION
**Pull request by ashrafmahmood**

### CODE REVIEW

**Comment by Haider8** [comment]
@ashrafmahmood  Semantic request is failing. Rename your commit message

**Comment by Haider8** [comment]
https://www.educative.io/edpresso/how-to-change-a-git-commit-message-after-a-push

**Comment by ashrafmahmood** [comment]
> @ashrafmahmood Semantic request is failing. Rename your commit message

'feat: Add ShopSearch component on large screen' 
Is this commit message correct?

**Comment by Haider8** [comment]
Mobile ShopView search is not working properly now. Have a look at it

**Comment by Haider8** [comment]
@ashrafmahmood Fix deepsource issue `Validation of JSX maximum depth` by taking nested jsx of depth more than 2 in a const like this `const foobar = <Foo><Bar /></Foo>` and then using that const in your main markup jsx

**Pull request merged**
